export const UPDATE_GALLERY = 'UPDATE_GALLERY';
export const SET_IMAGE = 'SET_IMAGE';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_MOBILE_NAV = 'OPEN_MOBILE_NAV';
export const CLOSE_MOBILE_NAV = 'CLOSE_MOBILE_NAV';

export const AUTHENTICATION_PENDING = 'AUTHENTICATION_PENDING';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';