export const Images = [
          {url: "paintings/Aaron_Mitchell_Painting_2011_700.jpg", set: "paintings"},
          {url: "paintings/Aaron_Mitchell_Painting_Does_This_Look_Good_700.jpg", set: "paintings"},
          {url: "paintings/Aaron_Mitchell_Painting_In_Between_700.jpg", set: "paintings"},
          {url: "paintings/Aaron_Mitchell_Painting_Is_It_Fresh_700.jpg", set: "paintings"},
          {url: "paintings/Aaron_Mitchell_Painting_Reach_700.jpg", set: "paintings"},
          {url: "paintings/Aaron_Mitchell_Painting_The_Black_Ring_700.jpg", set: "paintings"},
          {url: "paintings/Aaron_Mitchell_Painting_What_Did_You_Say_700.jpg", set: "paintings"},
          {url: "paintings/Aaron_Mitchell_Painting_Will_It_Stay_700.jpg", set: "paintings"},

          {url: "illustrations/Aaron_Mitchell_Best_Hotel_700.jpg", set: "illustrations"},
          {url: "illustrations/Aaron_Mitchell_Black_Gold_700.jpg", set: "illustrations"},
          {url: "illustrations/Aaron_Mitchell_Phish_Poster_700.jpg", set: "illustrations"},
          {url: "illustrations/Aaron_Mitchell_The_Ring_700.jpg", set: "illustrations"},
          {url: "illustrations/Aaron_Mitchell_Deer_700.jpg", set: "illustrations"},
          {url: "illustrations/Aaron_Mitchell_Covered_In_Bees_Shirt_700.jpg", set: "illustrations"},
          {url: "illustrations/Aaron_Mitchell_Stone_Church_Burger_700.jpg", set: "illustrations"},
          {url: "illustrations/Aaron_Mitchell_Baseball_Banner_700.jpg", set: "illustrations"},
          {url: "illustrations/Aaron_Mitchell_Cinderella_Sewing_700.jpg", set: "illustrations"},
          {url: "illustrations/Aaron_Mitchell_Cinderella_Carriage_700.jpg", set: "illustrations"},
          {url: "illustrations/Aaron_Mitchell_Heart_Of_Darkness_700.jpg", set: "illustrations"},
          {url: "illustrations/Aaron_Mitchell_Jess_700.jpg", set: "illustrations"},
          {url: "illustrations/Aaron_Mitchell_Lobster_700.jpg", set: "illustrations"},
          {url: "illustrations/Aaron_Mitchell_Manchester_American_Flag_700.jpg", set: "illustrations"},
          {url: "illustrations/Aaron_Mitchell_Rocky_Dog_700.jpg", set: "illustrations"},
          {url: "illustrations/Aaron_Mitchell_Self_Portrait_With_Basketball_700.jpg", set: "illustrations"},
          {url: "illustrations/Aaron_Mitchell_The_Watch_700.jpg", set: "illustrations"},
          {url: "illustrations/Aaron_Mitchell_Towers.jpg", set: "illustrations"},

          {url: "design/Aaron_Mitchell_Schillaci_Guitars_Logo_700.jpg", set: "design"},
          {url: "design/Aaron_Mitchell_Fuck_2016_700.jpg", set: "design"},
          {url: "design/Aaron_Mitchell_MacCallum_Group_Logo_700.jpg", set: "design"},
          {url: "design/Aaron_Mitchell_Ghost_Hunter_Logo_700.jpg", set: "design"},
          {url: "design/Aaron_Mitchell_MGS_Design_Logo_700.jpg", set: "design"},
          {url: "design/Aaron_Mitchell_Afghan_Strangers_Album_700.jpg", set: "design"},
          {url: "design/Aaron_Mitchell_Coastal_Farms_Logo_700.jpg", set: "design"},
          {url: "design/Aaron_Mitchell_Lobster_Fest_Shirt_700.jpg", set: "design"},
          {url: "design/Aaron_Mitchell_Rotary_Golf_Logo_700.jpg", set: "design"},
          {url: "design/Aaron_Mitchell_SL_Logix_Logo_700.jpg", set: "design"}
        ]